"""Engine (powertrain) curve — the ONE source of the car's torque/power.

The curve is produced by the 1dFVEngineSolver, a 1-D finite-volume gas-dynamics
engine simulator by Sun Devil Motorsports (SDM26, Arizona State University FSAE),
MIT licensed — https://github.com/NIXELFi/1dFVEngineSolver.  Vahan does not
recompute engine physics; it reads the solver's converged sweep (see
data/engine_curve_sdm26.json, regenerated by the sweep driver) and hands the
crank-torque table to the lap simulator and every dynamics consumer.

Honesty: the solver is SIMULATED, not dyno-validated.  Its trends are reliable
and its shape is physical, but the absolute level is approximate — anchor it to
a measured dyno pull when one exists (see anchor_curve_to_dyno).

Credits — Suspension & VD: Yu, Cougar Racing.  Powertrain: Sun Devil Motorsports.
"""
from __future__ import annotations
import json
import os
from typing import List, Optional, Tuple

_HERE = os.path.dirname(__file__)
_CURVE_JSON = os.path.join(_HERE, "data", "engine_curve_sdm26.json")

# Watermark / attribution strings (used by the GUI, binder and figures).
CREDIT_SUSPENSION = "Suspension & VD: Yu — Cougar Racing"
CREDIT_POWERTRAIN = ("Powertrain: Sun Devil Motorsports (SDM26) — "
                     "1dFVEngineSolver, MIT")
ENGINE_LABEL = "SDM26 1-D sim (Sun Devil Motorsports) — NOT dyno-validated"


def _load() -> Optional[dict]:
    try:
        with open(_CURVE_JSON, "r") as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def sdm26_engine_curve() -> Optional[Tuple[List[float], List[float], str]]:
    """(rpm[], crank torque N·m[], label) from the SDM26 solver sweep, or None
    if the curve file is missing.  This is the default engine for the whole
    tool — the backbone every lap-sim/dynamics engine number should read."""
    d = _load()
    if not d or not d.get("curve"):
        return None
    rpm = [float(p["rpm"]) for p in d["curve"]]
    tq = [float(p["brake_torque_Nm"]) for p in d["curve"]]
    if len(rpm) < 2:
        return None
    return rpm, tq, ENGINE_LABEL


def sdm26_peaks() -> Optional[dict]:
    """{'peak_power':{rpm,hp}, 'peak_torque':{rpm,Nm}} or None."""
    d = _load()
    if not d:
        return None
    return {"peak_power": d.get("peak_power"), "peak_torque": d.get("peak_torque")}


def anchor_curve_to_dyno(rpm, torque_Nm, dyno_peak_power_hp: float):
    """Scale a simulated crank-torque curve so its PEAK POWER matches a measured
    dyno figure, preserving the solver's SHAPE.  Use the day a real restricted-
    engine dyno number exists; until then the raw sim curve stands.

    Returns a new torque list scaled by (dyno_peak_hp / sim_peak_hp)."""
    import numpy as np
    r = np.asarray(rpm, float)
    t = np.asarray(torque_Nm, float)
    p_hp = t * r * 2 * np.pi / 60.0 / 745.7   # crank power at each point (hp)
    sim_peak = float(p_hp.max())
    if sim_peak <= 0:
        return list(t)
    return list(t * (float(dyno_peak_power_hp) / sim_peak))
